name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  REGISTRY: ghcr.io
  # IMAGE_NAME: simulator

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3
      - name: Login
        uses: docker/login-action@v2
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Buildx
        uses: docker/setup-buildx-action@v2
      - name: Meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository }}/capture-device-simulator:latest
          # tags: type=sha
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          # tags: rolandkappeler/hello:latest
          # tags: ${{ steps.meta.outputs.tags }}
          tags: ${{ env.REGISTRY }}/${{ github.repository }}/capture-device-simulator:latest
          # labels: ${{ steps.meta.outputs.labels }}
    #- name: Build the Docker image
    # run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
